stages:
  - unit_tests
  - test_flight

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

unit_tests:
  stage: unit_tests
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
      - fastlane ios test
  tags:
      - ios
      - gitlab-org

test_flight_build:
  stage: test_flight
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
      - fastlane ios beta
  tags:
      - ios
  only:
      - /^release-.*$/