stages:
  - unit_tests
  - test_flight

before_script:
  - gem install bundler
  - bundle install

unit_tests:
  dependencies: []
  stage: unit_tests
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
    script:
      - fastlane ios test
    tags:
      - ios

test_flight_build:
  dependencies: []
  stage: test_flight
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - fastlane ios beta
  tags:
    - ios
  only:
     - /^release-.*$/